name: TikTok Scraper

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Download memory.txt artifact (if exists)
      uses: actions/download-artifact@v4
      with:
        name: memory
        path: .

      continue-on-error: true

    - name: Install Python manually
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        python3 -m pip install --upgrade pip
        pip install requests

    - name: Run TikTok scraper
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        python3 tiktok.py

    - name: Upload updated memory.txt
      uses: actions/upload-artifact@v4
      with:
        name: memory
        path: memory.txt
